CREATE TABLE STUDENTS(
  S_NO NUMBER(3) PRIMARY KEY,
  S_NAME VARCHAR2(10) NOT NULL UNIQUE,
  S_YEAR VARCHAR2(6) NOT NULL,
  S_PHONE VARCHAR2(14) NOT NULL,
  S_P_PHONE VARCHAR2(14) NOT NULL
);
CREATE SEQUENCE S_SEQ
  START WITH 1
  INCREMENT BY 1 
  NOCACHE
  NOCYCLE;
  
CREATE TABLE TEACHERS(
  T_NO NUMBER PRIMARY KEY,
  T_NAME VARCHAR2(10) NOT NULL UNIQUE,
  T_PHONE VARCHAR2(14) NOT NULL,
  T_SALARY NUMBER(7) NOT NULL,
  T_HIREDATE DATE NOT NULL,
  T_RETIREDATE DATE
);
CREATE SEQUENCE T_SEQ
  START WITH 1
  INCREMENT BY 1 
  NOCACHE
  NOCYCLE;

CREATE TABLE LECTURE (
  L_NO NUMBER PRIMARY KEY,
  L_ROOM VARCHAR2(3) NOT NULL,
  L_TIME VARCHAR2(12) NOT NULL,
  T_NAME VARCHAR2(10) REFERENCES TEACHERS(T_NAME) NOT NULL,
  S_NAME VARCHAR2(10) REFERENCES STUDENTS(S_NAME) NOT NULL,
  L_CLASS VARCHAR2(6) NOT NULL,
  L_BOOK VARCHAR2(10) NOT NULL,
  L_TUITION NUMBER(7) NOT NULL
);
CREATE SEQUENCE L_SEQ
  START WITH 1
  INCREMENT BY 1 
  NOCACHE;
  
SELECT *
FROM LECTURE;

delete from lecture;

DROP TABLE lecture;
DROP SEQUENCE L_SEQ;

SELECT L_ROOM 호실, L_TIME 수업시간, TEACHERS.T_NAME 선생님, STUDENTS.S_NAME 학생, L_CLASS 수업등급, L_BOOK 수업교재, L_TUITION 수강료 
FROM LECTURE, STUDENTS, TEACHERS 
WHERE LECTURE.T_NAME = TEACHERS.T_NAME AND LECTURE.S_NAME = STUDENTS.S_NAME;